import type { ActiveCourses } from "../../types/activeCoursesTypes";
import { Client } from "@notionhq/client";
import { env } from "../../utils/env";

const notion = new Client({ auth: env.NOTION_API_TOKEN });

export const generateDefaultNotionPage = async (title: string) => {
  return await notion.pages.update({
    page_id: env.NOTION_PAGE_ID,
    properties: {
      title: {
        title: [
          {
            text: {
              content: title,
            },
          },
        ],
      },
    },
    icon: {
      type: "emoji",
      emoji: "📓",
    },
    cover: {
      type: "external",
      external: {
        url: "https://i.pinimg.com/originals/bb/e1/31/bbe131c33e257eaa23cf71323ecd95fc.jpg",
      },
    },
  });
};

export const propagateDefaultNotionInfoBlocks = async (pageId: string) => {
  return await notion.blocks.children.append({
    block_id: pageId,
    children: [
      {
        object: "block",
        type: "callout",
        callout: {
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  "IMPORTANT: This page is automatically generated by the Canvas Course Builder bot. If you want to edit it, please go to the bot and configure settings there.",
              },
              annotations: {
                color: "yellow_background",
              },
            },
          ],
        },
      },
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: [
            {
              type: "text",
              text: {
                content: "Welcome to the Canvas Course Builder bot!",
              },
            },
          ],
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  "Your courses are listed in the table below and you can click on the course name to view the course page. Your courses are automatically updated every day and you can see the current term in the title of the page. If you have any questions, please don't hesitate to get in touch. Have a great semester!",
              },
            },
          ],
        },
      },
    ],
  });
};

export const propagateDefaultNotionTableBlock = async (
  blockId: string,
  courses: ActiveCourses
) => {
  return await notion.blocks.children.append({
    block_id: blockId,
    children: [
      {
        object: "block",
        type: "divider",
        divider: {},
      },
      {
        object: "block",
        type: "table",
        table: {
          table_width: 2,
          has_column_header: false,
          has_row_header: true,
          children: [
            {
              object: "block",
              type: "table_row",
              table_row: {
                cells: [
                  [
                    {
                      type: "text",
                      text: {
                        content: "Course Name",
                        link: null,
                      },
                      annotations: {
                        bold: true,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: "default",
                      },
                    },
                  ],
                  [
                    {
                      type: "text",
                      text: {
                        content: "Grade",
                        link: null,
                      },
                      annotations: {
                        bold: true,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: "default",
                      },
                    },
                  ],
                ],
              },
            },
            {
              object: "block",
              type: "table_row",
              table_row: {
                cells: [
                  [
                    {
                      type: "text",
                      text: {
                        content: "English",
                        link: null,
                      },
                      annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: "default",
                      },
                    },
                  ],
                  [
                    {
                      type: "text",
                      text: {
                        content: "A (97.3)",
                        link: null,
                      },
                      annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: "green",
                      },
                    },
                  ],
                ],
              },
            },
          ],
        },
      },
    ],
  });
};

export const generateDefaultCourseNotionDatabase = async (
  pageId: string,
  courses: ActiveCourses
) => {
  const courseFormatted = courses.map((course: any) => {
    return {
      object: "block",
      type: "bulleted_list_item",
      bulleted_list_item: {
        rich_text: [
          {
            type: "text",
            text: {
              content: course.name,
              link: null,
            },
          },
        ],
      },
    };
  });

  return await notion.databases.create({
    parent: { page_id: pageId, type: "page_id" },
    title: [
      {
        type: "text",
        text: {
          content: "Courses",
          link: null,
        },
      },
    ],
    icon: {
      type: "emoji",
      emoji: "📚",
    },
    properties: {
      Name: {
        title: {},
      },
      Description: {
        rich_text: {},
      },
      "Course Code": {
        rich_text: {},
      },
      "Start Date": {
        type: "date",
        date: {},
      },
      "End Date": {
        type: "date",
        date: {},
      },
    },
    cover: {
      type: "external",
      external: {
        url: "https://i.pinimg.com/originals/bb/e1/31/bbe131c33e257eaa23cf71323ecd95fc.jpg",
      },
    },
  });
};
