import type { ActiveCourses } from "../../types/activeCoursesTypes";
import { Client } from "@notionhq/client";
import { getActiveCourses } from "../fetch/getActiveCourses";
import { env } from "../../utils/env";

// Types
import { Context } from "koa";
import { UpdatePageResponse } from "@notionhq/client/build/src/api-endpoints";

const notion = new Client({ auth: env.NOTION_API_TOKEN });

export const createMainNotionPage = async (ctx: Context) => {
  const courses: ActiveCourses = await getActiveCourses();
  // @ts-ignore
  const currTerm = courses[0].term.name;

  const defaultNotionPage = await notion.pages
    .update({
      page_id: env.NOTION_PAGE_ID,
      properties: {
        title: {
          title: [
            {
              text: {
                content: currTerm,
              },
            },
          ],
        },
      },
      icon: {
        type: "emoji",
        emoji: "📓",
      },
      cover: {
        type: "external",
        external: {
          url: "https://i.pinimg.com/originals/bb/e1/31/bbe131c33e257eaa23cf71323ecd95fc.jpg",
        },
      },
    })
    .then(async (page: UpdatePageResponse) => {
      await notion.blocks.children.append({
        block_id: page.id,
        children: [
          {
            object: "block",
            type: "callout",
            callout: {
              rich_text: [
                {
                  type: "text",
                  text: {
                    content:
                      "IMPORTANT: This page is automatically generated by the Canvas Course Builder bot. If you want to edit it, please go to the bot and configure settings there.",
                  },
                },
              ],
            },
          },
          {
            object: "block",
            type: "heading_2",
            heading_2: {
              rich_text: [
                {
                  type: "text",
                  text: {
                    content: "Welcome to the Canvas Course Builder bot!",
                  },
                },
              ],
            },
          },
          {
            object: "block",
            type: "paragraph",
            paragraph: {
              rich_text: [
                {
                  type: "text",
                  text: {
                    content:
                      "Your courses are listed in the table below and you can click on the course name to view the course page. Your courses are automatically updated every day and you can see the current term in the title of the page. If you have any questions, please don't hesitate to get in touch. Have a great semester!",
                  },
                },
              ],
            },
          },
        ],
      });
      return page;
    })
    .then(async (page: UpdatePageResponse) => {
      await notion.databases.create({
        parent: { page_id: page.id, type: "page_id" },
        title: [
          {
            type: "text",
            text: {
              content: "Courses",
              link: null,
            },
          },
        ],
        icon: {
          type: "emoji",
          emoji: "📚",
        },
        properties: {
          Name: {
            title: {},
          },
          Description: {
            rich_text: {},
          },
          "Course Code": {
            rich_text: {},
          },
          "Start Date": {
            type: "date",
            date: {},
          },
          "End Date": {
            type: "date",
            date: {},
          },
        },
      });
    })
    .finally(() => {
      ctx.status = 200;
      console.log("Done");
    })
    .catch((err) => {
      ctx.status = 500;
      console.log(err);
    });
};
